name: DAST

on:
  push:
    branches:
      - main
      
jobs:

  dast:
    runs-on: ubuntu-latest 
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          target: ${{ secrets.DAST_TARGET_URL }} 
